version: "3"
services:
 springapp:
  image: prathapva/javaspring:1
  ports:
  - 8080:8080
  environment:
  - MONGO_DB_HOSTNAME=mongo
  - MONGO_DB_USERNAME=devdb
  - MONGO_DB_PASSWORD=devdb@123
  networks:
  - springappbridge
 mongo:
  image: mongo
  volumes:
  - mongovol:/data/db
  environment:
  - MONGO_INITDB_ROOT_USERNAME=devdb
  - MONGO_INITDB_ROOT_PASSWORD=devdb@123
  networks:
  - springappbridge
volumes:
 mongovol:
networks:
 springappbridge:
  


